name: dungeon_master
description: "A Gemini-powered AI Dungeon RPG game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.5

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11

  # Google Gemini API
  google_generative_ai: ^0.4.7

  # Native splash screen
  flutter_native_splash: ^2.4.6
  lottie: ^3.3.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons8-google-48.png
    - assets/splash_animation.json
    - assets/icons/inventory.png
    - assets/icons/storyline.png
    - assets/icons/battle.png
    - assets/Wizard_bg.png
    # - assets/branding.png  # optional branding image

flutter_native_splash:
  color: "#000000"
  image: assets/splash_animation.json
  fullscreen: true
  android: false
  ios: true


    
