// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1XUxohDQGinsn9f2fCJ-1Yn81-YQU5L8',
    appId: '1:149348171609:web:14cc650296e05146411648',
    messagingSenderId: '149348171609',
    projectId: 'dungeon-is-master',
    authDomain: 'dungeon-is-master.firebaseapp.com',
    storageBucket: 'dungeon-is-master.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfGWWmof8y0aYkcBuUdaIn04hwxALc9V4',
    appId: '1:149348171609:android:485451cfa8cec73b411648',
    messagingSenderId: '149348171609',
    projectId: 'dungeon-is-master',
    storageBucket: 'dungeon-is-master.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIYMSGJTWlOrmVnm8Cl5nDN8AyllFfAWg',
    appId: '1:149348171609:ios:b0f47bd756c7a5b5411648',
    messagingSenderId: '149348171609',
    projectId: 'dungeon-is-master',
    storageBucket: 'dungeon-is-master.firebasestorage.app',
    iosBundleId: 'com.example.dungeonMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIYMSGJTWlOrmVnm8Cl5nDN8AyllFfAWg',
    appId: '1:149348171609:ios:b0f47bd756c7a5b5411648',
    messagingSenderId: '149348171609',
    projectId: 'dungeon-is-master',
    storageBucket: 'dungeon-is-master.firebasestorage.app',
    iosBundleId: 'com.example.dungeonMaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1XUxohDQGinsn9f2fCJ-1Yn81-YQU5L8',
    appId: '1:149348171609:web:82285edddf7a16b7411648',
    messagingSenderId: '149348171609',
    projectId: 'dungeon-is-master',
    authDomain: 'dungeon-is-master.firebaseapp.com',
    storageBucket: 'dungeon-is-master.firebasestorage.app',
  );
}
